//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Jun 21 14:10:48 2019 by ROOT version 6.16/00)
//      from the StreamerInfo in file lz_201906192219_000010_000000_raw.root
//////////////////////////////////////////////////////////


#ifndef DarkCountMCTruth_h
#define DarkCountMCTruth_h
class DarkCountMCTruth;

#include "Rtypes.h"

class DarkCountMCTruth {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned short iPMTIndex;    //
   double         fTime_ns;     //

   DarkCountMCTruth();
   DarkCountMCTruth(const DarkCountMCTruth & );
   virtual ~DarkCountMCTruth();

};
#endif
