//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Jun 21 14:10:48 2019 by ROOT version 6.16/00)
//      from the StreamerInfo in file lz_201906192219_000010_000000_raw.root
//////////////////////////////////////////////////////////


#ifndef DetectorVertexMCTruth_h
#define DetectorVertexMCTruth_h
class DetectorVertexMCTruth;

#include "Rtypes.h"
#include "TVector3.h"
#include "Riostream.h"
#include <vector>
#include <string>

class DetectorVertexMCTruth {

public:
// Nested classes declaration.

public:
// Data Members.
   TVector3    fPosition_mm;    //
   TVector3    fElectricFieldDirection;    //
   double      fTime_ns;                   //
   float       fEnergyDep_keV;             //
   float       fElectricFieldStrength_Vcm;    //
   unsigned int iRawS1Photons;                 //
   unsigned int iRawS2Photons;                 //
   unsigned int iRawScintPhotons;              //
   unsigned int iS1PhotonHits;                 //
   unsigned int iS2PhotonHits;                 //
   unsigned int iScintPhotonHits;              //
   unsigned int iDetectedS1Photons;            //
   unsigned int iDetectedS2Photons;            //
   unsigned int iDetectedScintPhotons;         //
   int          iS1PulseIndex;                 //
   int          iS2PulseIndex;                 //
   int          iScintillationPulseIndex;      //
   vector<int>  iArtifactPulseIndices;         //
   string       sParticleName;                 //
   string       sVolumeName;                   //

   DetectorVertexMCTruth();
   DetectorVertexMCTruth(const DetectorVertexMCTruth & );
   virtual ~DetectorVertexMCTruth();

};
#endif
